development:
  adapter: postgresql
  database: sample_app_development
  username: nkelty
  password: 
  host: localhost

test:
  adapter: postgresql
  database: sample_app_test
  username: nkelty
  password: 
  host: localhost

production:
  adapter: postgresql
  database: sample_app_production
  username: nkelty
  password: 
  host: localhost